name: Release Workflow

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Modular CLI
        run: |
            curl -s https://get.modular.com | sh -

      - name: Install Mojo
        run: |
          modular install mojo

      - name: Build Package
        run: |
          mojo package firehttp

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firehttp-package
          path: firehttp.mojopkg